stages:
  - lint
  - test
  - deploy

include:
  - project: 'sertit/groupware'
    file: '/ci_templates/arcgis_plugin.yaml'

variables:
  DOCKER_TLS_CERTDIR: ""

deploy:
  variables:
    PROJECT_PATH: $CI_PROJECT_PATH
    PROJECT_ROOT: "lsi"
    CENTRAL_REPOSITORY: sertit/arcgis-pro/sertit_atools
  stage: deploy
  trigger: sertit/arcgis-pro/sertit_atools
  rules:
    # Deploy if tag
    - if: $CI_COMMIT_TAG
      when: on_success
    # Manual deploy if commit to the default branch
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      when: manual

deploy_registry:
  image: python:latest
  stage: deploy
  script:
    - pip install build twine
    - python -m build
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/* --verbose
  rules:
    # Deploy if tag
    - if: $CI_COMMIT_TAG
      when: on_success
    # Manual deploy if commit to the default branch
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      when: manual
